### ISSUE TITLE
Switch to automatic generated version

### ISSUE THREAD

**Issue by realvictorprm** [giawa/opengl4csharp#11]
Hello giawa, Victor here ;)

I suggest to switch to an automatic generator for the bindings which should be produced with CppSharp. It's perfect for such purposes (I'm a contributor).

If automatic bindings are used things would follow this scheme:

1. Automatic bindings generated and saved into one file
2. Second file self written which contains object oriented wrappers for the functions.

**Comment by giawa** [comment]
Hey Victor,

I'll take a look at CppSharp.  The bindings are already automatically generated, including the documentation for the OpenGL calls.  It may make sense to move over to CppSharp if it supports something different, or simplifies the flow, but everything is already built with a single click.

The bindings aren't really what make this package interesting.  I think the VBO, VAO, Texture and SIMD support are what make it more interesting.  I think it is also neat that the entire package uses no unsafe code.

**Comment by realvictorprm** [comment]
Where do you generate the bindings automatically?
I didn't know that. If you Already have a generator it's not necessary of course

**Comment by giawa** [comment]
Binding generator is committed here:  1c95b51f22fe3c8cbedc4c4956889b80d8d87a8f
