### ISSUE TITLE
Shader Uniform Arrays

### ISSUE THREAD

**Issue by matthiasGmayer** [giawa/opengl4csharp#14]
Is there any way to set a shaders uniform arrays.
e.g.
glsl:
uniform vec3 lightPositions[10];

c#:
i can reference the array using shaderProgram["lightPositions[0]"], but i can only set the first value.
shaderProgram["lightPositions[1]"] or shaderProgram["lightPositions[]"] returns null.

**Comment by na2axl** [comment]
Hi @Spyion ,
I think that the method used to set shaders uniform arrays in opengl4csharp should be the same than the OpenGL API so you have to do:
```csharp
shaderProgram["lightPositions[0]"].SetValue(lights[0].Position);
shaderProgram["lightPositions[1]"].SetValue(lights[1].Position);
shaderProgram["lightPositions[2]"].SetValue(lights[2].Position);
// ...
shaderProgram["lightPositions[10]"].SetValue(lights[10].Position);
```
assuming that the variable `lights` is an array of `Light`.

Hope this will help you! :-)

**Comment by matthiasGmayer** [comment]
I don't know why, but this is not working.
I managed to set an array using
                Gl.ProgramUniform3fv(shaderProgram.ProgramID, Gl.GetUniformLocation(shaderProgram.ProgramID, "lightPositions[1]"), 3, positions[1].ToFloat());

**Comment by na2axl** [comment]
I've browsed the source code of opengl4csharp and it seems that the list of uniform variables is created once when the shader is compiled in OpenGL and not when the user want to request it (and this method work only for non-array variables, and maybe also for structs...)
So you can get the uniform location with `GL.GetUniformLocation(shaderProgram.ProgramID, "lightPositions[0]");` and set the value with `GL.Uniform3fv(location, yourXYZarray);` and do it for all others array members.
You can take a look on [this implementation](https://github.com/AlienEngine/AlienEngine/blob/features/rendering/AlienEngine/Shaders/ShaderProgram.cs)

Hope this will help you! :-)

**Comment by giawa** [comment]
Thanks for the comments (and for the slow response).  Yes, the uniform variables are currently only found at link time.  It should be expanded to work with other types, as mentioned.  However, this work hasn't been done yet.
