### ISSUE TITLE
Shadowmapping

### ISSUE THREAD

**Issue by Sorento** [giawa/opengl4csharp#4]
Hi, great job !!. There is an example of How to make Shadows with your engine. I mean Shadowmapping. I been trying without any success. Thank you.

**Comment by giawa** [comment]
This is a repository for the bindings themselves, not really for tutorials/etc.  I do have some tutorials here, but they do not include shadow mapping at this time :(

https://github.com/giawa/opengl4tutorials

I suggest checking out any OpenGL tutorials for shadow mapping.  They should be applicable to this library.  Best of luck!

http://www.opengl-tutorial.org/intermediate-tutorials/tutorial-16-shadow-mapping/
http://learnopengl.com/#!Advanced-Lighting/Shadows/Shadow-Mapping
