### ISSUE TITLE
How to subscribe key events to special keys?

### ISSUE THREAD

**Issue by gepbird** [giawa/opengl4csharp#41]
Most games use special keys to do certain actions, like sprinting with the left shift key.
How can I bind an event to a special key? I tried binding the event to every key from 0 to 256 using `OpenGL.Platform.Input.Subscribe`, but shift still did nothing.

**Comment by giawa** [comment]
Good question, and I don't have a good answer for the shift key.  It wasn't something I thought of when putting together the `Input` code.  In general, you can Subscribe to chords, which will allow you to capture things like ctrl+c, etc.  However, if you're wanting to subscribe to a modifier key like control, alt or shift on its own then you will need to hack on the Window.cs code a little bit.  Right now Window.cs captures SDLK_RSHIFT and SDLK_LSHIFT keyboard up/down events and stores their state in `rshift` and `lshift`.  You'll need to modify this code to call `Input.AddKey` on a modifier key press (similar to what the code already does for left/right/up/down).  Hopefully this helps!

**Comment by giawa** [comment]
Note:  In case you don't want shift to modify the keyboard character (you don't care to differentiate between 'a' and 'A') then you can remove the code setting `lshift` and `rshift` completely and just call `Input.AddKey`.

**Comment by gepbird** [comment]
Thanks! I'm willing to make a PR on this issue soon. It will be possible to subscribe to `SDL_keycode`s and not just `char`s.
