### ISSUE TITLE
Creating a .NET 5 branch, and making it the default branch.

### ISSUE THREAD

**Issue by ghost** [giawa/opengl4csharp#62]
Now that .NET 5 is out, and it is stable, why don't we create a new branch called 'dotnet5' and put a .NET 5 version on it, then make it the default branch?

**Comment by ghost** [comment]
I am tired I just realized my mistake, it is .NET Standard so it will work lol

**Comment by moroz69off** [comment]
Maybe it makes some sense, but my opinion is that many are still working in version 2 or 3
