### ISSUE TITLE
Missing ImageSharp

### ISSUE THREAD

**Issue by Khhs167** [giawa/opengl4csharp#63]
Hi! I am trying to load a texture, with new Texture() and when i do that i get an error that says that it cannot load ImageSharp verison="1.0.0.0". I have tried with including both ImageSharp latest and verison 1.0.0, why doesnt it work?

**Comment by giawa** [comment]
Hi there,

The opengl4csharp library requires ImageSharp for processing the bitmap image and converting it to the correct format/flipping it/etc.  This library should be included by default with opengl4csharp (you should see it in the lib folder).  Make sure the same ImageSharp included with the opengl4csharp project is included in the binary folder of your application.

That all being said, I'm going to update the library to use the new System.Drawing.Common nuget package.

Thanks!

**Comment by giawa** [comment]
I've just updated the dotnetcore branch to use System.Drawing.Common instead.  If you're up for it, try adding that nuget package and pull that latest opengl4csharp.  Hopefully that will do the trick!

**Comment by giawa** [comment]
I'm going to close this for now, but feel free to reopen the issue if you run into any problems.
